### ISSUE TITLE
Theoretical issue with concurrent caching

### ISSUE THREAD

**Issue by truist** [truist/gallery#2]
Maybe it could try to generate a thumbnail from a rotated image that is only partially written?

**Comment by schmonz** [comment]
Ran `rm -rf cache && mkdir cache`. The thumbnail that had been 2/3 gray is fixed, and now another image in the same album has a 100% gray thumbnail.

**Comment by truist** [comment]
1. Any warnings or errors in the logs?
1. Any other image sizes 100% gray?
1. Does it appear 100% gray if you view the image directly?
1. Is the cache dir owned by the right user (or have appropriate permissions)?

**Comment by truist** [comment]
There is an issue: if, during a slow upload, an album page is loaded, the thumbnails are generated with the partially-written files, leaving them partially grey. I haven't tested it, but I assume this is what also sometimes leads to non-auto-rotated files. (A fix will be forthcoming.)
